DROP TABLE tblPMember;
CREATE TABLE tblPMember (
	ID VARCHAR(20) NOT NULL,
	PWD VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	PROFILE VARCHAR(30) NOT NULL,
	PRIMARY KEY (ID)
);

insert into tblPMember 
values ('admin', '1234', 'eunbin', 'profile9.jpg');


DROP TABLE tblPBlog;
CREATE TABLE tblPBlog (
	NUM NUMBER(11),
	MESSAGE VARCHAR(255) default 'null',
	ID VARCHAR(20) NOT NULL,
	PDATE DATE NOT NULL,
	PHOTO VARCHAR(50) NOT NULL,
	HCNT NUMBER(11) DEFAULT 0 CHECK (HCNT >= 0),
	PRIMARY KEY (NUM)
);

DROP SEQUENCE tblPBlog_SEQ;
CREATE SEQUENCE tblPBlog_SEQ -- 게시번호를 위한 시퀀스 생성
INCREMENT BY 1 
START WITH 1
MINVALUE 1
MAXVALUE 10000
NOCYCLE;

DROP TABLE tblPReply;
CREATE TABLE tblPReply (
	RNUM NUMBER(11),
	NUM NUMBER(11) NOT NULL,
	ID VARCHAR(20) NOT NULL,
	RDATE DATE NOT NULL,
	COMMENTS VARCHAR(100) NOT NULL,
	PRIMARY KEY (RNUM)
);

DROP SEQUENCE tblPReply_SEQ;
CREATE SEQUENCE tblPReply_SEQ -- 게시번호를 위한 시퀀스 생성
INCREMENT BY 1 
START WITH 1
MINVALUE 1
MAXVALUE 10000
NOCYCLE;


DROP TABLE tblHeartReply;
CREATE TABLE tblHeartReply (
	HNUM NUMBER(11),
	NUM NUMBER(11) NOT NULL,
	ID VARCHAR(20) NOT NULL,
	HDATE DATE NOT NULL,
	PRIMARY KEY (HNUM)
);


DROP SEQUENCE tblHeartReply_SEQ;
CREATE SEQUENCE tblHeartReply_SEQ -- 게시번호를 위한 시퀀스 생성
INCREMENT BY 1 
START WITH 1
MINVALUE 1
MAXVALUE 10000
NOCYCLE;

select * from tblPMember;
select * from tblPBlog;
select * from tblPReply;
select * from tblHeartReply;