DROP TABLE REGISTER;

CREATE TABLE REGISTER (
	ID VARCHAR(20) NOT NULL,
	PWD VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) DEFAULT NULL,
	NUM1 VARCHAR(6) DEFAULT NULL,
	NUM2 VARCHAR(7) DEFAULT NULL,
	EMAIL VARCHAR(20) DEFAULT NULL,
	PHONE VARCHAR(20) DEFAULT NULL
);

INSERT INTO REGISTER
VALUES ('admin', '1234', 'eunbin', 
'901111', '2000000', 'qwer@gmail.com', '010-1234-5678');

select count(*) from register 
where id = 'admin' and pwd = '1234';

COMMIT
